### ISSUE TITLE
mnist hyperparameter tuning example fails

### ISSUE THREAD

**Issue by wfs** [GoogleCloudPlatform/cloudml-samples#3]
Hi. Running through the examples to ensure my environment was working and this example failed ...

---

```
(cloudml) paddlescoot@paddlescoot-Satellite-P870:~/google-cloud-ml/samples/mnist/hptuning$ gcloud beta ml jobs describe --project ${PROJECT_ID} ${JOB_NAME}
createTime: '2016-10-03T07:32:09Z'
endTime: '2016-10-03T07:44:00Z'
errorMessage: 'Too many hyperparameter tuning metrics were written by Hyperparameter
  Tuning Trial #1.'
jobId: mnist_hptuning_hullpod_central
startTime: '2016-10-03T07:32:12Z'
state: FAILED
trainingInput:
  args:
  - --train_data_paths=gs://cloud-ml-data/mnist/train.tfr.gz
  - --eval_data_paths=gs://cloud-ml-data/mnist/eval.tfr.gz
  - --output_path=gs://molten-method-145221-ml/mnist_hptuning_hullpod_central/output
  hyperparameters:
    goal: MAXIMIZE
    maxParallelTrials: 2
    maxTrials: 10
    params:
    - maxValue: 400.0
      minValue: 40.0
      parameterName: hidden1
      scaleType: UNIT_LINEAR_SCALE
      type: INTEGER
    - maxValue: 250.0
      minValue: 5.0
      parameterName: hidden2
      scaleType: UNIT_LINEAR_SCALE
      type: INTEGER
    - maxValue: 0.5
      minValue: 0.0001
      parameterName: learning_rate
      scaleType: UNIT_LOG_SCALE
      type: DOUBLE
  packageUris:
  - gs://molten-method-145221-ml/cloudmldist/1475479926/trainer-0.0.0.tar.gz
  pythonModule: trainer.task
  region: us-central1
  scaleTier: STANDARD_1
trainingOutput: {}
```

---
